version: '3'

networks:
  backend:
    driver: bridge # 可以让docker容器的互通 需要设置 - links postgres
  frontend:
    driver: bridge # 外网访问

services:
  honkaiacademyclubbacked:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:3008"
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    networks:
      - frontend
      - backend
  postgres:
    image: postgres:12-alpine
    container_name: xybdiy_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SymphonyIceAttack
    ports:
      - 5432:5432
    volumes:
      - /root/PostgreSQL/data:/var/lib/postgresql/data
    networks:
      - frontend
      - backend
